parrot_palace/config/routes.rb
Rails.application.routes.draw do
  resources :birds, only: [:index, :new, :create]
  get 'birds/index'

  get 'enroll/new'

  get 'birds/welcome'

  root 'birds#welcome'

end

parrot_palace/app/models/bird.rb
class Bird < ActiveRecord::Base
end

parrot_palace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

parrot_palace/app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  def index
    @birds = Bird.all
  end

  def new
    @bird = Bird.new
  end

  def create
    @bird = Bird.new(bird_params)
    if @bird.save
      redirect_to birds_url, notice: "Success!"
    else
      flash.now[:notice] = "Oops! Something goofed."
    end
  end

private
  def bird_params
    params.require(:bird).permit(:name, :age, :species)
  end


end

parrot_palace/app/controllers/enroll_controller.rb
class EnrollController < ApplicationController
  def new
  end
end

parrot_palace/app/helpers/application_helper.rb
module ApplicationHelper
end

parrot_palace/app/helpers/birds_helper.rb
module BirdsHelper
end

parrot_palace/app/helpers/enroll_helper.rb
module EnrollHelper
end

parrot_palace/app/views/birds/friends.html.erb
<h1>Enroll your bird today!</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Species</th>
      <th>Age</th>
    </tr>
  </thead>
<tbody>
  <% @birds.each do |bird| %>
    <tr>
      <td><%= bird.id %></td>
      <td><%= bird.name %></td>
      <td><%= bird.species %></td>
      <td><%= bird.age %></td>
    </tr>
    <% end %>
</tbody>
</table>

<%= link_to "Sign up!", new_bird_path %>

parrot_palace/app/views/birds/index.html.erb
<h1>Enroll your bird today!</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Species</th>
      <th>Age</th>
    </tr>
  </thead>
<tbody>
  <% @birds.each do |bird| %>
    <tr>
      <td><%= bird.id %></td>
      <td><%= bird.name %></td>
      <td><%= bird.species %></td>
      <td><%= bird.age %></td>
    </tr>
    <% end %>
</tbody>
</table>

<%= link_to "Sign up!", new_bird_path %>

parrot_palace/app/views/birds/welcome.html.erb
<h1>Welcome to Parrot Palace!</h1>
<p>Do you find yourself worrying about your beloved feathered friend sitting at home all day while you're at work, sadly chattering to no one and looking out the window wondering when the family is coming back home?</p>
<p>Here at Parrot Palace, we know how much you care about your birds! We provide daytime birdie daycare, as well as bird boarding for longer adventures. We're a team of avian fanatics who know how best to care for and provide companionship for your birdie buddies.</p>
<p>Interested in enrolling your pet in our daycare? <%= link_to "Visit our signup page", birds_index_path %> to get started!</p>

parrot_palace/app/views/enroll/new.html.erb
<h1>Add a Bird</h1>

<%= form_for @bird do |bird_fields| %>
  <%= bird_fields.label :name %>
  <%= bird_fields.text_field :name %>

  <%= bird_fields.label :species %>
<%= bird_fields.text_field :species %>

  <%= bird_fields.label :age %>
  <%= bird_fields.number_field :age %>

  <%= bird_fields.submit %>

  <% end %>

parrot_palace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParrotPalace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>