doggie_daycare/config/routes.rb
Rails.application.routes.draw do
  resources :owners
  resources :dogs
  resources :breeds

  get 'dogs/new'

  get 'puppytime/index'

  get 'puppytime/dogs'

  root 'puppytime#index'

end

doggie_daycare/app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :dogs
end

doggie_daycare/app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :owner
  belongs_to :breed

  validates :name, presence: true, length: {minimum: 1}
  validates :breed, presence: true, length: {minimum: 1}
  validates :age, presence: true, length: {minimum: 1}, numericality: { only_integer: true }
end

doggie_daycare/app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :dogs

  validates :name, presence: true, length: {minimum: 1}
  validates :phone, presence: true, length: {minimum: 7}, numericality: { only_integer: true }

end

doggie_daycare/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to dogs_url, notice: "Success!"
    else
      flash.now[:notice] = "Oops! Something goofed."
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    if @dog.update(dog_params)
      redirect_to dogs_url, notice: "Successfully updated!"
    else
      flash.now[:notice] = "Oops! Update not made."
      render :edit
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    if @dog.destroy
    redirect_to dogs_url, notice: "Successfully deleted!"
    else
    redirect_to dogs_url, notice: "Could not delete."
    end
  end

private
  def dog_params
    params. require(:dog).permit(:name, :age, :breed_id, :owner_id)
  end


end

doggie_daycare/app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :phone)
    end
end

doggie_daycare/app/controllers/puppytime_controller.rb
class PuppytimeController < ApplicationController
  def index
  end

  def dogs
  end
end

doggie_daycare/app/helpers/dogs_helper.rb
module DogsHelper
end

doggie_daycare/app/helpers/owners_helper.rb
module OwnersHelper
end

doggie_daycare/app/helpers/puppytime_helper.rb
module PuppytimeHelper
end

doggie_daycare/app/views/dogs/_form.html.erb
<%= bootstrap_form_for @dog do |dog_fields| %>

<div class="form">
  <div class="form-group">
  <%= dog_fields.label :name %>
  <%= dog_fields.text_field :name, class: "form-control", placeholder: "dog name" %>
  </div>

  <div class="form-group">
  <%= dog_fields.label :breed_id %>
  <%= dog_fields.collection_select :breed_id, Breed.all, :id, :name %>
  </div>

  <div class="form-group">
  <%= dog_fields.label :age %>
  <%= dog_fields.number_field :age, class: "form-control", placeholder: "dog age"  %>
  </div>

  <div class="form-group">
  <%= dog_fields.label :owner_id %>
  <%= dog_fields.collection_select :owner_id, Owner.all, :id, :name, class: "form-control" %>
  </div>


  <div class="actions">
    <%= dog_fields.submit class: "btn btn-secondary" %>
  </div>
   <% end %>
   </div>

doggie_daycare/app/views/dogs/edit.html.erb
<h1>Edit <%=@dog.name %>'s info</h1>

<%= render "form" %>

doggie_daycare/app/views/dogs/index.html.erb
<h1>Cool Dogs <i class="fa fa-paw"></i></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Owner</th>
    </tr>
  </thead>
<tbody>
  <% @dogs.each do |dog| %>
    <tr>
      <td><%= dog.id %></td>
      <td><%= dog.name %></td>
      <td><%= dog.breed.try(:name) %></td>
      <td><%= dog.age %></td>
      <td><%= dog.owner.try(:name) %></td>
      <td><%=link_to "show dog", dog_path(dog) %></td>
      <td><%=link_to "edit dog", edit_dog_path(dog) %></td>
      <td><%=link_to "delete", dog, method: :delete, data: {confirm: "are you sure?"} %></td>
    </tr>
    <% end %>
</tbody>
</table>

<div class = "linking">
<%= link_to "Add a dog!", new_dog_path %>
</div>
<br>
<div class = "linking">
<%= link_to "See owner list", owners_path %>
</div>

doggie_daycare/app/views/dogs/new.html.erb
<h1>Add a Dog</h1>

<%= render "form" %>

doggie_daycare/app/views/dogs/show.html.erb
<h1>Meet <%= @dog.name %></h1>

<p>
<strong>ID: </strong><%= @dog.id %>
</p>

<p>
<strong>Breed: </strong><%= @dog.breed %>
</p>

<p>
<strong>Age: </strong><%= @dog.age %>
</p>

<p>
<strong>Owner: </strong><%= @dog.owner.name %>
</p>

<p>
<strong>Date Added: </strong><%= @dog.created_at.stamp('02/14/2016') %>
</p>

<%= link_to "Back to dogs", dogs_path %>

doggie_daycare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoggieDaycare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

doggie_daycare/app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-secondary-outline" %>
  </div>
<% end %>

doggie_daycare/app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

doggie_daycare/app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Owners <i class="fa fa-paw"></i></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.phone %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class ="linking">
<%= link_to 'New Owner', new_owner_path %>
</div>
<br>
<div class = "linking">
<%= link_to "See dog list", dogs_path %>
</div>

doggie_daycare/app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

doggie_daycare/app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<p><strong>Dogs owned by <%= @owner.name.capitalize %></strong></p>
<ul>
  <% @owner.dogs.order('name').each do |dog| %>
    <li> <%= dog.name %> </li>
    <% end %>
</ul>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

doggie_daycare/app/views/puppytime/dogs.html.erb
<h1>LOOK AT THESE DOGS</h1>
<p>Look at them.</p>

<!-- <img src="../../assets/images/dog1.jpg">
<img src="/../assets/images/dog1">
<img src="/../assets/images/dog1">
<img src="/../assets/images/dog1">
 -->

doggie_daycare/app/views/puppytime/index.html.erb
<h1>Puppytime</h1>
<p>WE LOVE DOGS!</p>

<%= link_to "LOOK AT SOME DOGS", puppytime_dogs_path %>